window.t = {
    en: {
        brand: "Hussein Al-Naser",
        home: "Home",
        store: "Store",
        title: "Our Store",
        desc: "Browse our wide range of premium products",
        cartTitle: "Shopping Cart",
        total: "Total:",
        checkout: "Checkout",
        cats: { all: "All Categories", canned: "Canned Food", spices: "Spices", nuts: "Nuts", oils: "Oils & Ghee" },
        cartEmpty: "Your cart is empty",
        addToCart: "Add to Cart",
        notFound: "Product not found",
        qty: "Quantity",
        shipping: "Shipping Details",
        fname: "First Name",
        lname: "Last Name",
        address: "Address",
        city: "City",
        phone: "Phone Number",
        payment: "Payment Method",
        cardname: "Name on Card",
        cardnum: "Card Number",
        exp: "Expiry Date",
        pay: "Place Order",
        summary: "Order Summary",
        subtotal: "Subtotal:",
        shipFee: "Shipping Fee:",
        succTitle: "Order Successful!",
        succDesc: "Your order has been placed successfully and we will contact you shortly.",
        succBtn: "Back to Home"
    },
    ar: {
        brand: "مجموعة حسين الناصر",
        home: "الرئيسية",
        store: "المتجر",
        title: "متجرنا",
        desc: "تصفح تشكيلتنا الواسعة من المنتجات الفاخرة",
        cartTitle: "سلة المشتريات",
        total: "المجموع:",
        checkout: "إتمام الطلب",
        cats: { all: "جميع الأقسام", canned: "المعلبات", spices: "البهارات", nuts: "المكسرات", oils: "الزيوت والسمن" },
        cartEmpty: "السلة فارغة",
        addToCart: "إضافة للسلة",
        notFound: "المنتج غير موجود",
        qty: "الكمية",
        shipping: "تفاصيل الشحن",
        fname: "الاسم الأول",
        lname: "الاسم الأخير",
        address: "العنوان",
        city: "المدينة",
        phone: "رقم الهاتف",
        payment: "طريقة الدفع",
        cardname: "الاسم على البطاقة",
        cardnum: "رقم البطاقة",
        exp: "تاريخ الانتهاء",
        pay: "تأكيد الطلب",
        summary: "ملخص الطلب",
        subtotal: "المجموع الفرعي:",
        shipFee: "رسوم الشحن:",
        succTitle: "تم تأكيد طلبك بنجاح!",
        succDesc: "شكراً لتسوقك معنا. لقد استلمنا طلبك وسنقوم بالتواصل معك قريباً.",
        succBtn: "العودة للرئيسية"
    }
};

const lang = localStorage.getItem('appLang') || 'ar';
